/**
 * 🎥 AppWorking.tsx - 작업 버전 비디오 에디터 메인 컴포넌트
 * 
 * 실제 동작하는 비디오 에디터의 메인 컴포넌트로, 전체 UI 레이아웃과
 * 데이터 로딩 로직을 관리합니다. 타임라인, 플레이어, 미디어 라이브러리,
 * 속성 패널 등 모든 주요 컴포넌트를 조합하여 완전한 에디터 인터페이스를 제공합니다.
 * 
 * 핵심 기능:
 * - 드래그 & 드롭 지원 (react-dnd)
 * - 전역 키보드 이벤트 처리
 * - 자동 생성된 데이터 로딩 시스템
 * - 변경사항 추적 및 저장 상태 관리
 * - 페이지 나가기 전 경고 시스템
 * - 개발자 도구 (editorStore 전역 노출)
 * 
 * UI 레이아웃 구조:
 * - 헤더 (60px 고정)
 * - 상단: 사이드바(320px) + 플레이어 영역 (50%)
 * - 하단: 타임라인 영역 (50%)
 * - 우측: 속성 패널 (동적)
 * 
 * 관련 모듈:
 * - 1번 모듈: Timeline System (Timeline 컴포넌트)
 * - 7번 모듈: Remotion Integration (EditableVideoPlayer)
 * - 8번 모듈: State Management (useEditorStore)
 * - 6번 모듈: Auto Generation System (자동 생성 데이터 로딩)
 */
import React from 'react';
import { DndProvider } from 'react-dnd';
import { HTML5Backend } from 'react-dnd-html5-backend';
import { Header } from './components/Header';
import { MediaLibrary } from './components/MediaLibrary';
import { EditableVideoPlayer } from './components/player/EditableVideoPlayer';
import { Timeline } from './components/timeline/Timeline';
import { PropertiesPanel } from './components/PropertiesPanel';
import { KeyboardHandler } from './components/KeyboardHandler';
import { InfiniteLoopIndicator } from './components/common/InfiniteLoopIndicator';
import { useEditorStore } from './store/editorStore';
import { useBeforeUnload } from './hooks/useBeforeUnload';
import { applyOptimalDuration } from './utils/durationUtils';
import { globalAlert } from './utils/globalAlert';

/**
 * AppWorking 컴포넌트 - 실제 비디오 에디터 인터페이스
 * 
 * 주요 책임:
 * 1. 전체 UI 레이아웃 관리 (그리드 기반 레이아웃)
 * 2. 데이터 상태 관리 및 자동 저장/로딩
 * 3. 전역 이벤트 처리 (키보드, 드래그&드롭)
 * 4. 브라우저 예상 종료 예방 (beforeunload)
 * 5. 개발자 도구 제공 (디버깅 대상 노출)
 * 
 * 데이터 로딩 시스템:
 * - localStorage에서 autoGeneratedData 감지
 * - CustomEvent 'autoGeneratedDataReady' 리스너 등록
 * - 자동 데이터 검증 및 로딩
 * - 프로젝트 지속 시간 자동 계산 및 적용
 */
export const AppWorking: React.FC = () => {
  // 📊 데이터 상태 추적: 에디터 상태에서 변경사항 추적
  const hasUnsavedChanges = useEditorStore(state => state.hasUnsavedChanges);
  const markAsChanged = useEditorStore(state => state.markAsChanged);
  const markAsSaved = useEditorStore(state => state.markAsSaved);
  const loadProject = useEditorStore(state => state.loadProject);
  
  // 🧪 개발자 도구: editorStore를 window 객체에 노출 (디버깅 및 테스트용)
  // 개발 모드에서만 동작하며, 브라우저 콘솔에서 실시간 상태 디버깅 가능
  React.useEffect(() => {
    if (import.meta.env.DEV) {
      // 실시간 업데이트를 위해 함수로 접근
      (window as any).editorStore = useEditorStore.getState();
      (window as any).getEditorStore = () => useEditorStore.getState();
      console.log('🧪 editorStore가 window.editorStore에 노출되었습니다 (개발용)');
      console.log('🧪 실시간 접근: window.getEditorStore() 사용 가능');
    }
  }, []);
  
  // 디버깅: 변경사항 상태 로그
  React.useEffect(() => {
    console.log('🔍 hasUnsavedChanges 상태 변경:', hasUnsavedChanges);
  }, [hasUnsavedChanges]);
  
  // 페이지 떠나기 전 확인창 설정
  useBeforeUnload({ 
    hasUnsavedChanges,
    message: '편집 중인 비디오 프로젝트가 저장되지 않았습니다. 정말로 페이지를 떠나시겠습니까?' 
  });

  // 🎆 자동 생성 데이터 로딩 시스템
  // DataEditor에서 생성된 데이터를 CustomEvent로 수신하여 자동 로딩
  // localStorage에 저장된 데이터를 검증하고 프로젝트에 로딩
  React.useEffect(() => {
    const handleAutoGeneratedData = (event: CustomEvent) => {
      try {
        const { data, timestamp } = event.detail;
        console.log('🚀 자동 생성된 데이터 수신:', { data, timestamp });
        
        // localStorage에서 데이터 가져오기
        const storedData = localStorage.getItem('autoGeneratedData');
        if (storedData) {
          const parsedData = JSON.parse(storedData);
          
          // 데이터 검증
          if (parsedData.tracks && parsedData.projectSettings) {
            // 편집시간 자동 계산 및 적용
            const updatedProjectSettings = applyOptimalDuration(
              parsedData.projectSettings,
              parsedData.tracks
            );

            // 프로젝트 로드
            loadProject(
              parsedData.tracks || [],
              updatedProjectSettings,
              parsedData.bundles || [],
              parsedData.templateGroups || []
            );

            // 사용 후 정리
            localStorage.removeItem('autoGeneratedData');
            localStorage.removeItem('autoGeneratedDataTimestamp');

            // 성공 알림
            console.log('✅ 자동 생성된 데이터를 성공적으로 불러왔습니다!');
            globalAlert.showSuccess(`자동 생성된 데이터를 성공적으로 불러왔습니다!\n편집시간: ${updatedProjectSettings.duration}초로 자동 설정되었습니다.`);
          } else {
            console.error('❌ 유효하지 않은 데이터 형식:', parsedData);
            globalAlert.showError('유효하지 않은 데이터 형식입니다.');
          }
        }
      } catch (error) {
        console.error('❌ 자동 생성된 데이터 처리 실패:', error);
        globalAlert.showError('자동 생성된 데이터를 처리하는데 실패했습니다.');
      }
    };

    // 이벤트 리스너 등록
    window.addEventListener('autoGeneratedDataReady', handleAutoGeneratedData as EventListener);

    return () => {
      window.removeEventListener('autoGeneratedDataReady', handleAutoGeneratedData as EventListener);
    };
  }, [loadProject]);

  return (
    <DndProvider backend={HTML5Backend}>
      <KeyboardHandler />
      
      <div style={{
        width: '100vw',
        height: '100vh',
        background: 'linear-gradient(135deg, #0f0f23 0%, #1a1a2e 50%, #16213e 100%)', // 더 매력적인 다크 그라디언트
        display: 'flex',
        flexDirection: 'column',
        margin: 0,
        padding: 0
      }}>
        {/* 헤더 */}
        <div style={{
          height: '60px',
          background: 'linear-gradient(135deg, #1e1e2e 0%, #2a2a3e 100%)', // 세련된 그라디언트
          borderBottom: '2px solid #4a4a6a',
          boxShadow: '0 2px 10px rgba(0, 0, 0, 0.3)' // 그림자 추가
        }}>
          <Header />
        </div>

        {/* 메인 영역 */}
        <div style={{
          flex: 1,
          display: 'flex',
          flexDirection: 'column',
          minHeight: 0
        }}>
          {/* 상단: 사이드바 + Player - 50% */}
          <div style={{
            height: 'calc((100vh - 60px) / 2)', // 헤더 제외하고 50%
            display: 'flex',
            minHeight: 200 // 최소 높이 보장
          }}>
            {/* 사이드바 */}
            <div style={{
              width: '320px',
              background: 'linear-gradient(180deg, #1a1a2e 0%, #16213e 100%)', // 블루 그라디언트
              borderRight: '2px solid #4a4a6a',
              boxShadow: '2px 0 10px rgba(0, 0, 0, 0.2)' // 그림자
            }}>
              <MediaLibrary />
            </div>

            {/* Player 영역 */}
            <div style={{
              flex: 1,
              position: 'relative',
              minWidth: 0,
              background: 'linear-gradient(135deg, #0f3460 0%, #0e4b99 30%, #2e86ab 100%)', // 아름다운 블루 그라디언트
            }}>
              <EditableVideoPlayer />
            </div>
          </div>

          {/* 하단: 타임라인 - 50% */}
          <div style={{
            height: 'calc((100vh - 60px) / 2)', // 헤더 제외하고 50%
            background: 'linear-gradient(180deg, #16213e 0%, #0f3460 100%)', // 타임라인 그라디언트
            borderTop: '2px solid #4a4a6a',
            minHeight: '200px', // 최소 높이
            boxShadow: '0 -2px 10px rgba(0, 0, 0, 0.2)' // 위쪽 그림자
          }}>
            <Timeline />
          </div>
        </div>
        
        <PropertiesPanel />
      </div>
      
      {/* 무한루프 방지 인디케이터 */}
      <InfiniteLoopIndicator />
    </DndProvider>
  );
};
